/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MarkdownAlert: typeof import('./src/components/MarkdownAlert.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.11.1_f85d4f90837e14df74b83e3894bc5115/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UContainer: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.11.1_f85d4f90837e14df74b83e3894bc5115/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UIcon: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.11.1_f85d4f90837e14df74b83e3894bc5115/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UPage: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.11.1_f85d4f90837e14df74b83e3894bc5115/node_modules/@nuxt/ui/dist/runtime/components/Page.vue')['default']
    UPageBody: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.11.1_f85d4f90837e14df74b83e3894bc5115/node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue')['default']
  }
}
